#访问端口
server:
  port: 8082
spring:
  application:
    name: bms
  datasource:
    url: jdbc:mysql://121.40.163.240:3306/bms?autoReconnect=true&amp;useUnicode=true&amp
    driver-class-name: org.gjt.mm.mysql.Driver
    username: root
    password: Glpr0p1!
    hikari:
      maximum-pool-size: 50
      leak-detection-threshold: 16000
      connection-timeout: 30000
      idle-timeout: 25000
      minimum-idle: 5
    #--------------------Druid 连接池配置 end-----------------------------
#mybatis配置
mybatis:
  #配置mapper文件所在的位置
  mapper-locations: classpath:mybatis/mappers/*.xml
  #配置实体类的位置，这样在mapper文件中的返回值类型直接写User即可（否则要加上包名.类名）
  type-aliases-package: com.bms.entity

#pagehelper配置
pagehelper:
  offset-as-page-num: true
  row-bounds-with-count: true
  reasonable: true
#配置 logback
logging:
  config: classpath:log/logback-spring-dev.xml
#监控
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always



